import os
from dotenv import load_dotenv
import google.generativeai as genai
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from .models import State, Party, StatePartyMapping, Event, Faq
from .serializers import StateSerializer, PartySerializer, EventSerializer

load_dotenv()

# Configure Gemini AI Studio
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
gemini_model = None
if GEMINI_API_KEY and GEMINI_API_KEY != "your_gemini_api_key_here":
    genai.configure(api_key=GEMINI_API_KEY)
    gemini_model = genai.GenerativeModel('gemini-1.5-flash')

def api_response(success, message, data=None):
    # Matches the exact signature of ApiResponse.java
    return Response({
        "success": success,
        "message": message,
        "data": data,
        "timestamp": "2026-05-01T00:00:00" # Dummy timestamp format
    })

@api_view(['GET'])
def get_states(request):
    states = State.objects.all()
    serializer = StateSerializer(states, many=True)
    return api_response(True, "States retrieved successfully", serializer.data)

@api_view(['GET'])
def get_parties_by_state(request, state_name):
    try:
        state = State.objects.get(state_name__iexact=state_name)
        mappings = StatePartyMapping.objects.filter(state=state)
        parties = [m.party for m in mappings]
        serializer = PartySerializer(parties, many=True)
        return api_response(True, f"Parties for {state_name} retrieved successfully", serializer.data)
    except State.DoesNotExist:
        return Response({"success": False, "message": "State not found"}, status=404)

@api_view(['GET'])
def get_events(request):
    events = Event.objects.all()
    serializer = EventSerializer(events, many=True)
    return api_response(True, "Events feed retrieved successfully", serializer.data)

@api_view(['POST'])
def chat(request):
    user_message = request.data.get('message', '').lower()
    
    # 1. Google AI Studio (Gemini) LLM Route
    if gemini_model:
        try:
            prompt = (
                "You are the Smart Election Assistant for India. Answer the user's question politely and accurately, "
                "focusing entirely on election, voting, and political intelligence in India. Keep answers concise. "
                f"User Question: {user_message}"
            )
            response = gemini_model.generate_content(prompt)
            return api_response(True, "Response generated by Gemini AI", {
                "reply": response.text,
                "timestamp": "2026-05-02T00:00:00"
            })
        except Exception as e:
            print(f"Gemini API Error: {e}")
            # Fall through to local logic if API fails
            
    # 2. Check for dynamic State Intelligence first
    states = State.objects.all()
    for state in states:
        if state.state_name.lower() in user_message:
            answer = f"The current Chief Minister of {state.state_name} is {state.current_cm}."
            if state.current_deputy_cm and state.current_deputy_cm != 'N/A':
                answer += f" The Deputy CM is {state.current_deputy_cm}."
            answer += f" The state has {state.lok_sabha_seats} Lok Sabha seats and {state.vidhan_sabha_seats} Vidhan Sabha seats."
            return api_response(True, "Dynamic State Response generated", {
                "reply": answer,
                "timestamp": "2026-05-02T00:00:00"
            })

    # 2. Fallback to FAQ Keyword Matching
    faqs = Faq.objects.all()
    best_match = None
    max_score = 0
    
    for faq in faqs:
        keywords = [k.strip().lower() for k in faq.keywords.split(',')]
        score = sum(1 for k in keywords if k in user_message)
        if score > max_score:
            max_score = score
            best_match = faq
            
    if best_match and max_score > 0:
        answer = best_match.answer
    else:
        answer = (
            "I'm your Election Assistant. I can help you with: \n"
            "1. Voting Process & IDs\n"
            "2. Polling Booths\n"
            "3. State Statistics (e.g. 'Who is the CM of Maharashtra?')\n"
            "Please ask a question!"
        )
        
    return api_response(True, "Response generated", {
        "reply": answer,
        "timestamp": "2026-05-02T00:00:00"
    })
